### ISSUE TITLE
LegacyScript execution fails since f9329e2

### ISSUE THREAD

**Issue by seijikun** [PlayOnLinux/POL-POM-5#12]
Since commit f9329e2, the execution of LegacyScripts fails on my Notebook. This is the exception I am receiving:
```
Exception in thread "MainThread" Traceback (most recent call last):
  File "/mnt/extern/Coding/Java/PlayOnLinux/POL-POM-5/src/main/python/v4wrapper.py", line 25, in <module>
    from SetupWindow.SetupWindowNetcatServer import SetupWindowNetcatServer
  File "/mnt/extern/Coding/Java/PlayOnLinux/POL-POM-5/src/main/python/SetupWindow/SetupWindowNetcatServer.py", line 21, in <module>
    from SetupWindowNetcatCommandParser import SetupWindowNetcatCommandParser
  File "/mnt/extern/Coding/Java/PlayOnLinux/POL-POM-5/src/main/python/SetupWindow/SetupWindowNetcatCommandParser.py", line 22, in <module>
    from com.playonlinux.framework import EnvironementHelper
ImportError: cannot import name EnvironementHelper
Exception in thread "Thread-8" Traceback (most recent call last):
  File "/mnt/extern/Coding/Java/PlayOnLinux/POL-POM-5/src/main/python/v4wrapper.py", line 25, in <module>
    from SetupWindow.SetupWindowNetcatServer import SetupWindowNetcatServer
  File "/mnt/extern/Coding/Java/PlayOnLinux/POL-POM-5/src/main/python/SetupWindow/SetupWindowNetcatServer.py", line 21, in <module>
    from SetupWindowNetcatCommandParser import SetupWindowNetcatCommandParser
  File "/mnt/extern/Coding/Java/PlayOnLinux/POL-POM-5/src/main/python/SetupWindow/SetupWindowNetcatCommandParser.py", line 22, in <module>
    from com.playonlinux.framework import EnvironementHelper
ImportError: cannot import name EnvironementHelper
```
The new python-scripts work flawlessly.

**Comment by qparis** [comment]
This is interesting, so it means than python needs to have access to the constructor. Reverting back as it was only a good practice

**Comment by qparis** [comment]
My mistake, it was infact a refactor problem. (A spellcheck has been made).
Keeping the constructor private

**Comment by seijikun** [comment]
And I've been searching for the issue for multiple hours...
Life can be so easy sometimes.

**Comment by qparis** [comment]
Problem fixed :)
