### ISSUE TITLE
When I'm trying to run playonlinux 5 I'm getting this error:

### ISSUE THREAD

**Issue by mimi89999** [PlayOnLinux/POL-POM-5#144]
michel@debian:~/POL-POM-5$ java -jar target/playonlinux-5.0-SNAPSHOT-jar-with-dependencies.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/playonlinux/app/PlayOnLinuxApp : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by yawkat** [comment]
You need to use java 8.

**Comment by mimi89999** [comment]
Before I did:
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

**Comment by yawkat** [comment]
But did you actually use the java 8 executable

**Comment by mimi89999** [comment]
How can I check that?

**Comment by yawkat** [comment]
java -version

**Comment by mimi89999** [comment]
michel@debian:~/POL-POM-5$ java -version 
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by mimi89999** [comment]
Is it the good version?

**Comment by qparis** [comment]
Nope, the good version is Java 8
Try $JAVA_HOME/bin/java instead of Java

**Comment by mimi89999** [comment]
michel@debian:~/POL-POM-5/POL-POM-5/POL-POM-5$ /usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar target/playonlinux-5.0-SNAPSHOT-jar-with-dependencies.jar
worked
Thank you
