### ISSUE TITLE
Problem when executing...

### ISSUE THREAD

**Issue by iZeus83** [PlayOnLinux/POL-POM-5#158]
Hi all, 

I'm using linux mint 17.2 amd64

I have a successfull compilation using the latest version of jdk 8 using the official "jdk-8u51-linux-x64.tar.gz". But then when I run the file compiled using this comand:  "java -jar playonlinux-5.0-SNAPSHOT-jar-with-dependencies.jar" then I get this message and can't open the program.

*********************************************************************************

Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
	at com.sun.javafx.application.LauncherImpl$$Lambda$31/817978763.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Input stream must not be null
	at javafx.scene.image.Image.validateInputStream(Image.java:1109)
	at javafx.scene.image.Image.<init>(Image.java:694)
	at com.playonlinux.ui.impl.javafx.mainwindow.LeftButton.<init>(LeftButton.java:35)
	at com.playonlinux.ui.impl.javafx.mainwindow.engines.ViewEngines.drawSideBar(ViewEngines.java:65)
	at com.playonlinux.ui.impl.javafx.mainwindow.engines.ViewEngines.<init>(ViewEngines.java:48)
	at com.playonlinux.ui.impl.javafx.mainwindow.MainWindow.setUpWindow(MainWindow.java:55)
	at com.playonlinux.ui.impl.javafx.JavaFXApplication.start(JavaFXApplication.java:40)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
	at com.sun.javafx.application.LauncherImpl$$Lambda$60/884915910.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl$$Lambda$56/1839075738.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$58/646900084.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$57/154219674.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$46/430565046.run(Unknown Source)
	... 1 more

**Comment by qparis** [comment]
Do you have the latest version of the snapshot? This problem should have been fixed

**Comment by iZeus83** [comment]
Ok, thank you qparis. Now I can run fine :+1:
