### ISSUE TITLE
Failure trying to install Age of Empires III: Complete Collection

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#527]
`TypeError: (((newWine().wizard(setupWizard).architecture(this.wineArchitecture)).version(this._wineVersion)).prefix(this._name)).luna is not a function in <eval> at line number 106`

Stacktrace
```
javax.script.ScriptException: TypeError: (((new Wine().wizard(setupWizard).architecture(this._wineArchitecture)).version(this._wineVersion)).prefix(this._name)).luna is not a function in <eval> at line number 106
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.playonlinux.scripts.nashorn.NashornEngine.eval(NashornEngine.java:27)
	at com.playonlinux.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:17)
	at com.playonlinux.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: <eval>:106 TypeError: (((new Wine().wizard(setupWizard).architecture(this._wineArchitecture)).version(this._wineVersion)).prefix(this._name)).luna is not a function
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$37$2500$\^eval\_.go(<eval>:106)
	at jdk.nashorn.internal.scripts.Script$19$\^eval\_.:program(<eval>:4)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
	... 10 more
```

Ubuntu 16.10. Do note that I have the old version of POL installed alongside this (I think it's the version from the Ubuntu repositories), would that be causing the errors?

**Comment by plata** [comment]
You can have PoL 4 and PoL 5 installed at the same time without a problem. This issue should be in [Scripts](https://github.com/PlayOnLinux/Scripts).
@qparis do you have to include luna in the script? SteamScript includes it already but the error is reported in SteamScript:106.

**Comment by Ads20000** [comment]
I can get past this error after using `git pull`, sorry for wasting your time

**Comment by qparis** [comment]
Luna is just here to make wine windows prettier. Not very important
