### ISSUE TITLE
Lots of errors in console when opening the app

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#564]
```
[pool-3-thread-1] WARN org.phoenicis.apps.ClasspathApplicationsSource - Error while reading resource directory
[pool-2-thread-1] WARN org.phoenicis.apps.ClasspathApplicationsSource - Error while reading resource directory
java.io.FileNotFoundException: class path resource [com/phoenicis/repository/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
	at org.phoenicis.apps.ClasspathApplicationsSource.fetchInstallableApplications(ClasspathApplicationsSource.java:54)
	at org.phoenicis.apps.TeeApplicationsSource.fetchInstallableApplications(TeeApplicationsSource.java:48)
	at org.phoenicis.apps.MultipleApplicationsSource.fetchInstallableApplications(MultipleApplicationsSource.java:45)
	at org.phoenicis.apps.ConfigurableApplicationSource.fetchInstallableApplications(ConfigurableApplicationSource.java:47)
	at org.phoenicis.apps.FilterApplicationsSource.fetchInstallableApplications(FilterApplicationsSource.java:50)
	at org.phoenicis.apps.ApplicationsSource.fetchInstallableApplications(ApplicationsSource.java:35)
	at org.phoenicis.apps.BackgroundApplicationsSource.lambda$fetchInstallableApplications$0(BackgroundApplicationsSource.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.io.FileNotFoundException: class path resource [com/phoenicis/repository/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
	at org.phoenicis.apps.ClasspathApplicationsSource.fetchInstallableApplications(ClasspathApplicationsSource.java:54)
	at org.phoenicis.apps.TeeApplicationsSource.fetchInstallableApplications(TeeApplicationsSource.java:48)
	at org.phoenicis.apps.MultipleApplicationsSource.fetchInstallableApplications(MultipleApplicationsSource.java:45)
	at org.phoenicis.apps.ConfigurableApplicationSource.fetchInstallableApplications(ConfigurableApplicationSource.java:47)
	at org.phoenicis.apps.FilterApplicationsSource.fetchInstallableApplications(FilterApplicationsSource.java:50)
	at org.phoenicis.apps.ApplicationsSource.getCategory(ApplicationsSource.java:60)
	at org.phoenicis.apps.ApplicationsSource.getApplication(ApplicationsSource.java:64)
	at org.phoenicis.apps.ApplicationsSource.getScript(ApplicationsSource.java:42)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:35)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:71)
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:37)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[pool-2-thread-1] WARN org.phoenicis.apps.ClasspathApplicationsSource - Error while reading resource directory
java.io.FileNotFoundException: class path resource [com/phoenicis/repository/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
	at org.phoenicis.apps.ClasspathApplicationsSource.fetchInstallableApplications(ClasspathApplicationsSource.java:54)
	at org.phoenicis.apps.TeeApplicationsSource.fetchInstallableApplications(TeeApplicationsSource.java:48)
	at org.phoenicis.apps.MultipleApplicationsSource.fetchInstallableApplications(MultipleApplicationsSource.java:45)
	at org.phoenicis.apps.ConfigurableApplicationSource.fetchInstallableApplications(ConfigurableApplicationSource.java:47)
	at org.phoenicis.apps.FilterApplicationsSource.fetchInstallableApplications(FilterApplicationsSource.java:50)
	at org.phoenicis.apps.ApplicationsSource.getCategory(ApplicationsSource.java:60)
	at org.phoenicis.apps.ApplicationsSource.getApplication(ApplicationsSource.java:64)
	at org.phoenicis.apps.ApplicationsSource.getScript(ApplicationsSource.java:42)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:35)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:71)
	at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program([Functions, Engines, Wine]:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:77)
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:37)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[pool-2-thread-1] WARN org.phoenicis.apps.ClasspathApplicationsSource - Error while reading resource directory
java.io.FileNotFoundException: class path resource [com/phoenicis/repository/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
	at org.phoenicis.apps.ClasspathApplicationsSource.fetchInstallableApplications(ClasspathApplicationsSource.java:54)
	at org.phoenicis.apps.TeeApplicationsSource.fetchInstallableApplications(TeeApplicationsSource.java:48)
	at org.phoenicis.apps.MultipleApplicationsSource.fetchInstallableApplications(MultipleApplicationsSource.java:45)
	at org.phoenicis.apps.ConfigurableApplicationSource.fetchInstallableApplications(ConfigurableApplicationSource.java:47)
	at org.phoenicis.apps.FilterApplicationsSource.fetchInstallableApplications(FilterApplicationsSource.java:50)
	at org.phoenicis.apps.ApplicationsSource.getCategory(ApplicationsSource.java:60)
	at org.phoenicis.apps.ApplicationsSource.getApplication(ApplicationsSource.java:64)
	at org.phoenicis.apps.ApplicationsSource.getScript(ApplicationsSource.java:42)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:35)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:71)
	at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program([Functions, Engines, Wine]:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:77)
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:37)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[pool-2-thread-1] WARN org.phoenicis.apps.ClasspathApplicationsSource - Error while reading resource directory
java.io.FileNotFoundException: class path resource [com/phoenicis/repository/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
	at org.phoenicis.apps.ClasspathApplicationsSource.fetchInstallableApplications(ClasspathApplicationsSource.java:54)
	at org.phoenicis.apps.TeeApplicationsSource.fetchInstallableApplications(TeeApplicationsSource.java:48)
	at org.phoenicis.apps.MultipleApplicationsSource.fetchInstallableApplications(MultipleApplicationsSource.java:45)
	at org.phoenicis.apps.ConfigurableApplicationSource.fetchInstallableApplications(ConfigurableApplicationSource.java:47)
	at org.phoenicis.apps.FilterApplicationsSource.fetchInstallableApplications(FilterApplicationsSource.java:50)
	at org.phoenicis.apps.ApplicationsSource.getCategory(ApplicationsSource.java:60)
	at org.phoenicis.apps.ApplicationsSource.getApplication(ApplicationsSource.java:64)
	at org.phoenicis.apps.ApplicationsSource.getScript(ApplicationsSource.java:42)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:35)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:71)
	at jdk.nashorn.internal.scripts.Script$4$\^eval\_.:program([Functions, Filesystem, Extract]:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:77)
	at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program([Functions, Engines, Wine]:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:77)
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:37)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[pool-2-thread-1] WARN org.phoenicis.apps.ClasspathApplicationsSource - Error while reading resource directory
java.io.FileNotFoundException: class path resource [com/phoenicis/repository/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
	at org.phoenicis.apps.ClasspathApplicationsSource.fetchInstallableApplications(ClasspathApplicationsSource.java:54)
	at org.phoenicis.apps.TeeApplicationsSource.fetchInstallableApplications(TeeApplicationsSource.java:48)
	at org.phoenicis.apps.MultipleApplicationsSource.fetchInstallableApplications(MultipleApplicationsSource.java:45)
	at org.phoenicis.apps.ConfigurableApplicationSource.fetchInstallableApplications(ConfigurableApplicationSource.java:47)
	at org.phoenicis.apps.FilterApplicationsSource.fetchInstallableApplications(FilterApplicationsSource.java:50)
	at org.phoenicis.apps.ApplicationsSource.getCategory(ApplicationsSource.java:60)
	at org.phoenicis.apps.ApplicationsSource.getApplication(ApplicationsSource.java:64)
	at org.phoenicis.apps.ApplicationsSource.getScript(ApplicationsSource.java:42)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:35)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:71)
	at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program([Functions, Engines, Wine]:4)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:77)
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:37)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[pool-2-thread-1] WARN org.phoenicis.apps.ClasspathApplicationsSource - Error while reading resource directory
java.io.FileNotFoundException: class path resource [com/phoenicis/repository/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
	at org.phoenicis.apps.ClasspathApplicationsSource.fetchInstallableApplications(ClasspathApplicationsSource.java:54)
	at org.phoenicis.apps.TeeApplicationsSource.fetchInstallableApplications(TeeApplicationsSource.java:48)
	at org.phoenicis.apps.MultipleApplicationsSource.fetchInstallableApplications(MultipleApplicationsSource.java:45)
	at org.phoenicis.apps.ConfigurableApplicationSource.fetchInstallableApplications(ConfigurableApplicationSource.java:47)
	at org.phoenicis.apps.FilterApplicationsSource.fetchInstallableApplications(FilterApplicationsSource.java:50)
	at org.phoenicis.apps.ApplicationsSource.getCategory(ApplicationsSource.java:60)
	at org.phoenicis.apps.ApplicationsSource.getApplication(ApplicationsSource.java:64)
	at org.phoenicis.apps.ApplicationsSource.getScript(ApplicationsSource.java:42)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:35)
	at org.phoenicis.scripts.interpreter.ScriptFetcher.getScript(ScriptFetcher.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:71)
	at jdk.nashorn.internal.scripts.Script$5$\^eval\_.:program([Functions, Net, Download]:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:77)
	at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program([Functions, Engines, Wine]:4)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$3(NashornEngineFactory.java:77)
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:37)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by qparis** [comment]
Should be fixed

**Comment by Brainzyy** [comment]
@qparis I compiled again and they are still there.

**Comment by qparis** [comment]
Can you show the trace?

**Comment by Brainzyy** [comment]
@qparis Nevermind, I forgot to delete the .Phoenicis folder. Fixed.
