### ISSUE TITLE
No bean named 'appsSource'

### ISSUE THREAD

**Issue by feanor12** [PlayOnLinux/POL-POM-5#669]
I tried running the lol script and I got this:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'appsSource' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:698)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$0(NashornEngineFactory.java:66)
	at jdk.nashorn.internal.scripts.Script$Recompilation$87$74$\^eval\_.WineShortcut([Functions, Shortcuts, Wine]:5)
	at jdk.nashorn.internal.scripts.Script$Recompilation$47$564$\^eval\_.go([Functions, QuickScript, InstallerScript]:92)
	at jdk.nashorn.internal.scripts.Script$19$\^eval\_.:program(<eval>:17)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by madoar** [comment]
Is this only the case for the lol script, or does this happen for other scripts too?

**Comment by qparis** [comment]
@plata commit in POL-POM-5 might have broken this

**Comment by feanor12** [comment]
I tried to install notepad++ and got the same error. I think it happens when to script creates the shortcut.

**Comment by madoar** [comment]
This sounds like we need some tests for the scripts. Do you have any ideas how to test the parts of the code that work with the scripts?

**Comment by plata** [comment]
@madoar have a look at #472
