### ISSUE TITLE
Error when deselecting "Installed" or "Not installed" in the Engines Tab 

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#719]
When deselecting "Installed" or "Not installed" in the sidebar of the "Engines" tab I get the following exception:
```
Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.removeAll(Collections.java:1068)
	at org.phoenicis.engines.CombinedEnginesFilter.apply(CombinedEnginesFilter.java:67)
	at org.phoenicis.javafx.controller.engines.EnginesController.lambda$null$0(EnginesController.java:65)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by plata** [comment]
When did this break? It used to be working. Can't even debug: As soon as I place a breakpoint before that line, the error disappears. Maybe some threading issue?

**Comment by madoar** [comment]
I don't know when it broke. I just know that it's not connected to #720.
I guess it's connected to the used list. If you use a list generated by `Arrays.asList()` you can't add items to the list. If you do you get the previous exception.

**Comment by plata** [comment]
Could it be related to #684?

**Comment by plata** [comment]
At least ea27e30d0171eded8625ae6cbe9eb5691339fbc5 works.

**Comment by plata** [comment]
The `unmodifiableList` is in `EngineCategoryDTO`:
```Java
this.subCategories = Collections.unmodifiableList(builder.subCategories);
```

Probably it would make sense to use an `ObservableList` like for the apps for the filter (see #685). What do you think?

**Comment by madoar** [comment]
I would prefer using `ObservableList`s only in the javafx projects, because they shipped with javafx.

**Comment by plata** [comment]
Yes. Would you like to try it (you did it for the apps already so you know what has to be done)?

**Comment by madoar** [comment]
If you want, I can implement the filter with a `FilterList` from javafx. 
If we do this I would also suggest to incorporate the `SearchBar` to the filter (like it's done for the "Apps" tab). The question is how should the search term be applied to the engines?

**Comment by plata** [comment]
Does it make sense to search? If you think we should do that, I would suggest to show all engines of the current category which contain the string. E.g. select Wine, then search "2." gives you all versions (in several tabs) which contain "2.".

**Comment by madoar** [comment]
I'm not sure if it's useful to search, but we currently have a searchbar it would be a shame to not use it

**Comment by plata** [comment]
Well it doesn't hurt if we have it ;)
