### ISSUE TITLE
extract .cab with CAB PARSER

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#744]
https://github.com/dorkbox/CabParser

**Comment by plata** [comment]
@qparis could you add some more information?

**Comment by qparis** [comment]
The idea behind this ticket is to be able to extract .cab files so that we can avoid depending on cabextract tool.

We already started to write some piece of code but it is really incomplete

**Comment by plata** [comment]
Where can that code be found?

**Comment by qparis** [comment]
https://github.com/PlayOnLinux/POL-POM-5/tree/ce5a63719b10082f641ffaf8ba3116db8d13da28/phoenicis-tools/src/main/java/org/phoenicis/tools/archive/cab

**Comment by madoar** [comment]
Where do we want to have the extraction code to be located?
I guess that we want to call it from inside the `Scripts` repository right? If this is correct I think we'll need to add a new function to the Scripts repository and maybe some additional code in Java to make the access to `CabParser` easier and more comfortable. 
How should the interface to access the cab files look like?

**Comment by plata** [comment]
We have an interface already: <https://github.com/PlayOnLinux/Scripts/blob/master/Functions/Filesystem/Extract/script.js>.

**Comment by madoar** [comment]
I guess all arguments in `CabExtract` (wizard, archive, message, to) are `String`s? 
Should I add an additional java class with an `extract` method to make the cab extraction more typesafe?

**Comment by plata** [comment]
The `wizard` is a `SetupWizard`, `archive` is a `Resource` (check in scripts which use this).

**Comment by madoar** [comment]
Is there a test cab file, which we can use to write a test for the cab extractor functionality?

**Comment by plata** [comment]
Why not use one of the files which are already extracted with the current `CabExtract` in Scripts (e.g. the corefonts Verb)?

**Comment by madoar** [comment]
Ok, I've just done some experimentation with `CabExtract` on the `arial32.exe` file for the corefonts Verb.
It seems `CabExtract` alone won't be enough.
When I try to open `arial32.exe` with `CabExtract` I get the following stacktrace:
```
17:25:28.204 [main] ERROR org.phoenicis.tools.archive.Cab - Couldn't open the cab file '/home/marc/Dokumente/Play on Linux/POL-POM-5/phoenicis-tools/target/test-classes/org/phoenicis/tools/archive/arial32.exe'
dorkbox.cabParser.CorruptCabException: Missing header signature
	at dorkbox.cabParser.structure.CabHeader.read(CabHeader.java:91) ~[CabParser-2.11.jar:na]
	at dorkbox.cabParser.CabParser.readData(CabParser.java:105) ~[CabParser-2.11.jar:na]
	at dorkbox.cabParser.CabParser.<init>(CabParser.java:76) ~[CabParser-2.11.jar:na]
	at org.phoenicis.tools.archive.Cab.extract(Cab.java:28) ~[classes/:na]
	at org.phoenicis.tools.archive.CabExtractorTest.testCabExtraction(CabExtractorTest.java:35) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
```

After a look at the man page of `cabextract` I discovered the following sentence:
```
 cabextract is a program that un-archives files in the Microsoft cabinet
       file format (.cab) or any binary file which contains an embedded  cabi‐
       net file (frequently found in .exe files).
```

Reading this I think the problem is, that the file is an `exe` file, which contains one or more cab files.
I've done a quick search for `java extract exe` but found nothing useful. Any ideas?

**Comment by qparis** [comment]
I may be mistaken, but I think it is because their CabHeader class is reading from the begining of the file. In a .exe, the cab is not necessarely at the begining in the file.

**Comment by madoar** [comment]
This is possible, still I'm quite unsure how to continue with this, because it doesn't seem feasible to me to change the code of `CabExtract`. My guess is that we need a library to extract `exe` files, but I'm note sure such a library exists for java.
Do you have an idea?

**Comment by qparis** [comment]
It is definately possible

**Comment by madoar** [comment]
Ok, I've just taken a look at the GitHub page of `CabParser` and discovered that they have moved their repository to another git host https://git.dorkbox.com/dorkbox/CabParser.
In addition they seem to have released a new version of `CabParser`, maybe we can give this issue a try again.
