### ISSUE TITLE
Unable to run on archlinux

### ISSUE THREAD

**Issue by ycmjason** [PlayOnLinux/POL-POM-5#771]
I have followed the [build instructions](https://github.com/PlayOnLinux/POL-POM-5/wiki/Build). At the last step when I try to do `sh phoenics.sh` it failed. 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/phoenicis/javafx/JavaFXApplication : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by madoar** [comment]
Hi, this normally means, that you have a too old java version.
To run POL 5 you need Java 8 with Javafx. 
Can you please run `java --version` and tell us which java version you use?

**Comment by ycmjason** [comment]
Thank you for spotting this so quickly. 

I just switched to archlinux from ubuntu and didn't know that you have to switch the java version once you have installed java8 on the machine. it works now.

I found this particularly useful for anyone who had the same problem.
https://wiki.archlinux.org/index.php/java#Switching_between_JVM

**Comment by ycmjason** [comment]
not really i think. but would be nice if included maybe?

**Comment by plata** [comment]
Wiki is updated.
