### ISSUE TITLE
Error when opening POL 5

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#846]
When opening POL 5 I currently get the following stacktrace:
```
[ForkJoinPool.commonPool-worker-2] WARN org.phoenicis.repository.repositoryTypes.ClasspathRepository - Error while reading resource directory
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3833)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3774)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2849)
	at org.phoenicis.repository.repositoryTypes.ClasspathRepository.buildCategory(ClasspathRepository.java:75)
	at org.phoenicis.repository.repositoryTypes.ClasspathRepository.fetchInstallableApplications(ClasspathRepository.java:60)
	at java.util.stream.Collectors.lambda$toConcurrentMap$59(Collectors.java:1473)
	at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
I think the reason for this may be my currently empty library.

**Comment by plata** [comment]
But why in `ClasspathRepository`?

**Comment by madoar** [comment]
I don't know, can you reproduce the error?

**Comment by plata** [comment]
No. I renamed my shortcuts folder but did not get this.

**Comment by plata** [comment]
@madoar any steps to reproduce this (I cannot currently)?

**Comment by madoar** [comment]
I simply start POL 5 via IntelliJ, then this stacktrace is shown.
If no one else can reproduce this, it looks like the reason is somewhere in my POL 5 settings/configuration files?

**Comment by plata** [comment]
Do you have spaces in a path maybe?

**Comment by madoar** [comment]
Yes `.../Play on Linux/...`

**Comment by plata** [comment]
Can you try if it works if there are no spaces?

**Comment by madoar** [comment]
I've just tested POL 5 on the master branch with a path containing no spaces and I get the same error.
Now after a few commits in between, compared to the version from which I got the last stacktrace, the stacktrace now looks like this:
```
[ForkJoinPool.commonPool-worker-2] WARN org.phoenicis.repository.repositoryTypes.ClasspathRepository - Error while reading resource directory
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3833)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3774)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2849)
	at org.phoenicis.repository.repositoryTypes.ClasspathRepository.buildCategory(ClasspathRepository.java:80)
	at org.phoenicis.repository.repositoryTypes.ClasspathRepository.fetchInstallableApplications(ClasspathRepository.java:62)
	at java.util.stream.Collectors.lambda$toConcurrentMap$59(Collectors.java:1473)
	at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by plata** [comment]
Can you debug to see what's going on?

**Comment by madoar** [comment]
I've just added a debug output to line 80 in `ClasspathRepository` it seems like `jsonCategoryFile` contains two different values for me:

- `/org/phoenicis/repository/Functions/category.json`
- `/org/phoenicis/repository/DefaultRepositoryManager.class/category.json`

I'm not sure where and how the second value is created, but it's wrong and should lead to the given exception

**Comment by plata** [comment]
How does your repository list look like? (in the properties)

**Comment by madoar** [comment]
`application.repository.configuration=file\:/home/marc/Dokumente/Play on Linux/Scripts;git+https\://github.com/PlayOnLinux/Scripts;git+https\://github.com/PlayOnLinux/Oldwares;classpath\:///org/phoenicis/repository;`

**Comment by plata** [comment]
Does it work if you remove the `classpath` one?

**Comment by madoar** [comment]
Yes, when I remove the classpath repository I can start POL 5 without the stacktrace

**Comment by plata** [comment]
Ok. With classpath, I have the same error. Why doesn't the unittest find this?

**Comment by madoar** [comment]
I don't know.

We have another problem too:
If you remove the main scripts repository, POL 5 will start with a lot of errors.

**Comment by plata** [comment]
One problem is related to generic engines: We have to parse the repository for the available engines before including them.
