### ISSUE TITLE
NullPointerException at startup

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#878]
On the current master branch I get the following stacktrace when starting POL 5:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at org.phoenicis.javafx.views.mainwindow.apps.ApplicationFilter.lambda$filter$5(ApplicationFilter.java:153)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at org.phoenicis.javafx.views.mainwindow.apps.ApplicationFilter.filter(ApplicationFilter.java:153)
	at javafx.collections.transformation.FilteredList.addRemove(FilteredList.java:268)
	at javafx.collections.transformation.FilteredList.sourceChanged(FilteredList.java:144)
	at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at org.phoenicis.javafx.views.common.ExpandedList.sourceChanged(ExpandedList.java:199)
	at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.transformation.FilteredList.sourceChanged(FilteredList.java:147)
	at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at org.phoenicis.javafx.views.mainwindow.apps.ViewApps.lambda$populate$5(ViewApps.java:133)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by madoar** [comment]
This results in an empty list in the "Apps" tab.

**Comment by plata** [comment]
I think your repository is not up to date.

**Comment by madoar** [comment]
I've experimented a bit, it seems like this error disappears when I remove the Oldware repository.

**Comment by plata** [comment]
I also had this error. I can't remember which PR it was but there was an update which is required. Probably the same changes have to be done for the Oldware repository.

**Comment by plata** [comment]
I think it was the renaming of `requiresNoCd` to `requiresPatch`.

**Comment by madoar** [comment]
Hmm, what exactly is the reason for a separate repository `Oldwares`?
Can't we integrate them in `Scripts`?

**Comment by qparis** [comment]
Because there are some people that don't really care about these old ware and in a long term, we could have hundred of them.
I think repositories are also a great way to categorize the scripts

**Comment by madoar** [comment]
What exactly does the `Oldwares` repository contain?

**Comment by plata** [comment]
Seems like something is wrong with the `include`. It's crashing in Nashorn when trying to evaluate `include(["Functions", "Engines", "Wine"]);`.

**Comment by plata** [comment]
@madoar do you still have this with the current master?

**Comment by madoar** [comment]
Nope, no more startup errors ;)
